FROM golang:1.24.5-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o server main.go


FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/server .
COPY public ./public

EXPOSE 8080

CMD ["./server"]
