FROM golang:1.24.5-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd/restful ./cmd/restful

RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/restful/api.go


FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/server .

# If there is anything that needs to be coppied for public like images csv and other
# make it here
# COPY public ./public

CMD ["./server"]
